name: Publish Workflow / Complete
description: It finish publishing

inputs:
  branch:
    description: target branch for git push
    required: true
  prev_version:
    description: package's prev version
    required: true
  next_version:
    description: package's next version
    required: true
  package_name:
    description: package's name
    required: true
  token:
    description: token for write access to repository
    required: true
  npm_token:
    description: token for publish package to NPM
    required: true
  npm_tag:
    description: tag for NPM artifact
    required: false
    default: latest

outputs:
  prev_version:
    description: Previous version of package
    value: ${{ steps.internal_id_prev_version.outputs.value }}

runs:
  using: composite
  steps:
    - name: Commit and tag
      run: |
        git add -A
        git commit -m 'bump(${{ inputs.package_name }}): from ${{ inputs.prev_version }} to ${{ inputs.next_version }}'
        git tag ${{ inputs.package_name }}@${{ inputs.next_version }}
      shell: bash

    - name: Pushing changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        tags: true

    - name: Setup NPM Auth Token to .yarnrc.yml
      run: |
        yarn config set npmAlwaysAuth true
        yarn config set npmAuthToken $NPM_AUTH_TOKEN
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm_token }}
      shell: bash

    - name: Publish release of ${{ inputs.package_name }}
      run: yarn workspace ${{ inputs.package_name }} npm publish --tag ${{ inputs.npm_tag }}
      shell: bash
