name: 'Pull Request'

# > Про 'pull_request_target' и про риски его использования можно ознакомиться в статье по ссылке ниже
# > https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
# При 'pull_request_target' свойство `github.ref` будет соответствовать `refs/head/master`, поэтому необходимо
# вручную перебивать его на `github.event.pull_request.number` там, где это необходимо.
#
# Пример:
# ```
# - uses: actions/checkout@v3
#   with:
#     ref: refs/pull/${{ github.event.pull_request.number }}/merge
# ```
on: ['pull_request_target']

concurrency:
  group: pr-common-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  linters:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Setting up the repository environment
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn run build

      - name: Run lint:ci command
        run: yarn run lint:ci

      - name: Upload lint scripts artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-scripts-output
          path: lint-results.json

  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Setting up the repository environment
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn run build

      - name: Run tests for the specified workspace
        run: yarn run test:ci

      - name: Upload test artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-output
          path: test-results.json

  report_ci:
    if: ${{ always() }}
    needs:
      - linters
      - test
    runs-on: ubuntu-latest
    name: Report CI results
    steps:
      - name: Download lint scripts artifact
        uses: actions/download-artifact@v3
        with:
          name: lint-scripts-output

      - name: Download test artifact
        uses: actions/download-artifact@v3
        with:
          name: test-output

      - name: Push reports
        uses: VKCOM/gh-actions/VKUI/reporter@main
