name: 'Pull Request'

on: ['pull_request']

concurrency:
  group: pr-common-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  linters:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting up the repository environment
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn run build

      - name: Run lint:ci command
        run: yarn run lint:ci

      - name: Upload lint scripts artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-scripts-output
          path: lint-results.json

  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting up the repository environment
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn run build

      - name: Run tests for the specified workspace
        run: yarn run test:ci

      - name: Upload test artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-output
          path: test-results.json

  report_ci:
    if: ${{ always() }}
    needs:
      - linters
      - test
    runs-on: ubuntu-latest
    name: Report CI results
    steps:
      - name: Download lint scripts artifact
        uses: actions/download-artifact@v3
        with:
          name: lint-scripts-output

      - name: Download test artifact
        uses: actions/download-artifact@v3
        with:
          name: test-output

      - name: Push reports
        uses: VKCOM/gh-actions/VKUI/reporter@main
